### PR TITLE
Czech hyphenation patterns

### PR DESCRIPTION
**Pull request by tomas-vl**
Hello, this adds Czech hyphenation patterns. These are not [the patterns from CTAN which are usually included with TeX](https://www.ctan.org/pkg/hyph-utf8). Instead these are [a new set of Czechoslovak patterns](https://github.com/tensojka/cshyphen) by Petr and Ondřej Sojka.

I hope everything works fine; I am still learning Rust.

### CODE REVIEW

**Comment by laurmaedje** [comment]
Thanks, nice that alternative patterns are available! I did not know about them. Would you mind also updating the language table in the README?

**Comment by tomas-vl** [comment]
I've added Czech to the table and I've sorted it alphabetically, if you don't mind.

These new patterns were created for both Czech and Slovak, so they're a bit bigger than the original patterns (50 KiB vs 25 KiB), but according to the authors "the resulting Czechoslovak patterns hyphenate Czech and Slovak much better than the former single language patterns", so I think the bigger size is worth it.

**Comment by laurmaedje** [comment]
Does Slovak have its own language code? If so, we might need to add an alias.

**Comment by tomas-vl** [comment]
It does (sk, slk), but standalone Slovak patterns are already included.

**Comment by laurmaedje** [comment]
okay, and are the existing ones better or are the Czech ones pereferrable?

**Comment by tomas-vl** [comment]
It's hard to tell, the authors unfortunately didn't compare the new patterns to the included Slovak patterns, see table 4 in [the article](https://www.fi.muni.cz/usr/sojka/papers/sojka-sojka-tug-2021.pdf). They are _likely_ better (2000 vs 8000 patterns).

**Comment by laurmaedje** [comment]
Let's leave it for now (making it an alias would feel wrong, and support for sharing patterns across non-aliasing languages would need to be implemented first). But we can keep an eye on this and maybe replace them down the road.

**Comment by laurmaedje** [comment]
Thanks!

**Pull request merged**
